"""Export the verification sample that Bob's api.py reads (GET /api/verify).

usage: python -m harness.export_sample [--seed 2026] [--rows 2000] [--out PATH]

Writes service/sheetshift_ho3/data/verify_sample_2026.json.gz: the boundary and lint-guided
rows plus a seeded sample of random rows (2,000 in total), each with its 14 inputs and the
43 recorded oracle values. When a decision-patched oracle exists its values are the expected
ones (oracle_variant "patched"), otherwise the original oracle's. Deterministic (gzip mtime
0), under 1 MB. This file is generated by the harness and is read-only for Bob.

JSON encoding: dates {"date": "YYYY-MM-DD"}, errors {"error": "#N/A"}, blank null.

Standard library only; Python 3.8+.

Author: Claude Code (AI agent) — scaffold; see ATTRIBUTION.md
"""
import argparse
import json
import os
import random
import sys

from harness import common as C
from harness.compare import TOLERANCE

LIMIT_BYTES = 1000000


def default_out(seed):
    return os.path.join(C.ROOT, "service", "sheetshift_ho3", "data", "verify_sample_%d.json.gz" % seed)


def pick(meta, n_rows, seed):
    fixed = meta.get("fixed_rows", 0)
    rng = random.Random(seed * 104729 + n_rows)
    rest = rng.sample(range(fixed, meta["n"]), max(0, min(n_rows - fixed, meta["n"] - fixed)))
    return list(range(fixed)) + sorted(rest)


def build(seed, n_rows):
    meta, policies = C.load_inputs(seed)
    patched = C.load_oracle(seed, patched=True)
    oracle = patched if patched is not None else C.load_oracle(seed)
    if oracle is None:
        raise SystemExit("golden oracle missing: run `make oracle`")
    gmeta = C.read_json(C.golden_paths(seed)["meta"])
    variant = "patched" if patched is not None else "original"
    tags = meta.get("fixed_tags", [])
    rows = []
    for i in pick(meta, n_rows, seed):
        rows.append({"row": i + 2, "boundary": i < meta.get("fixed_rows", 0),
                     "tag": tags[i] if i < len(tags) else None,
                     "policy": {k: C.encode(policies[i].get(k)) for k in C.inputs()},
                     "expected": {k: C.encode(oracle[i].get(k)) for k in C.outputs()}})
    lints = [{"id": l["id"], "type": l["type"], "cell": l.get("cells") or l["cell"],
              "output_name": l["output_name"], "row": l.get("row"),
              "decision": C.decision_id_for_lint(l["id"])} for l in C.lints()]
    return {
        "_about": "Verification sample for GET /api/verify: synthetic policies for Example Mutual "
                  "Insurance Co. (FICTIONAL) with the recorded LibreOffice oracle values. "
                  "Generated by harness/export_sample.py; read-only for the service.",
        "oracle": gmeta.get(variant, {}).get("label") or C.ORACLE_LABEL.format(version="?", seed=seed),
        "oracle_variant": variant, "seed": seed, "golden_rows": meta["n"],
        "boundary_rows": meta.get("fixed_rows", 0), "tolerance": TOLERANCE,
        "encoding": {"date": {"date": "YYYY-MM-DD"}, "error": {"error": "#N/A"}, "blank": None},
        "inputs": C.inputs(), "outputs": C.outputs(), "lints": lints,
        "hashes": {"inputs": C.sha256_file(C.golden_paths(seed)["inputs"]),
                   "oracle": C.sha256_file(C.golden_paths(seed)["oracle_patched" if patched is not None else "oracle"])},
        "rows": rows,
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description="Export the /api/verify sample")
    ap.add_argument("--seed", type=int, default=C.DEFAULT_SEED)
    ap.add_argument("--rows", type=int, default=2000)
    ap.add_argument("--out")
    ap.add_argument("--service", default=C.DEFAULT_SERVICE, help="accepted for uniformity; unused")
    a = ap.parse_args(argv)
    doc = build(a.seed, a.rows)
    out = a.out or default_out(a.seed)
    C.write_json(out, doc)
    size = os.path.getsize(out)
    print(json.dumps({"out": C.rel(out), "rows": len(doc["rows"]), "oracle_variant": doc["oracle_variant"],
                      "bytes": size, "sha256": C.sha256_file(out)}))
    if size >= LIMIT_BYTES:
        print("export_sample: %d bytes exceeds the 1 MB limit" % size, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
